initialization
initialize
addedPoints := OrderedCollection new.
removedPoints := OrderedCollection new.
removedLines := OrderedCollection new.
addedLines := OrderedCollection new.
newPositionsDict := Dictionary new.
removedLinesAfterActionDo := OrderedCollection new.
oldPositionsDict := Dictionary new.
labelTransforms := Dictionary new.
oldLabels := OrderedCollection new.
oldToNewLabels := Dictionary new.
addedLabels := OrderedCollection new.